version: '3.8'

services:
  # SQL Server Service
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: agentservicedb
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=yourStrong(!)Password
    ports:
      - "1435:1433"
    volumes:
      - sql_data:/var/opt/mssql
    networks:
      - mtogo-network

  # Application Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: agentservicecontainer
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:8080
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=agentservicedb;Database=agentdb;User Id=sa;Password=yourStrong(!)Password;TrustServerCertificate=True;
    ports:
      - "8081:8080"
    depends_on:
      - db
    networks:
      - mtogo-network

  # Prometheus Service
  prometheus:
    image: prom/prometheus:latest
    container_name: agentserviceprometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9091:9090"
    networks:
      - mtogo-network

  # Grafana Service
  grafana:
    image: grafana/grafana:latest
    container_name: agentservicegrafana
    ports:
      - "3001:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - mtogo-network

# Volumes to persist data
volumes:
  sql_data:
  grafana_data:

# Networks to connect the services
networks:
  mtogo-network:
    driver: bridge
